### ISSUE TITLE
Chip is mislabeled in the schematic.

### ISSUE THREAD

**Issue by Funda** [sparkfun/Motor_Driver-Dual_TB6612FNG#1]
The schematic for both 09457 and 13845 label the chip incorrectly. We have the chip itself labeled "TB6621FNG" instead of "TB6612FNG".  Also, the schematic on the 13845 product page is the old v10 version.

**Comment by ElhemEnohpi** [comment]
There's now an erroneous package in EasyEDA, tagged "SparkFun", which seems to be spreading this to other schematics:
https://easyeda.com/component/TB6621FNG-LmyKIGDBz
https://s3.amazonaws.com/digistump-resources/files/9adf044f_motor.pdf

**Comment by ToniCorinne** [comment]
@ericorosel can you take a look at this? If we need to fix this on the updated board version, I'd like to address this.

**Comment by ericorosel** [comment]
@ToniCorinne the v11 schematic symbol/package was updated to the symbol/package in the "Sparkfun-" library during the revision. The symbol in v11 has the correct name

**Comment by pbbob** [comment]
@ericorosel @Funda @ElhemEnohpi @ToniCorinne @nseidle  where is the library for this part, and/or the older version? i cant find the part in the library in this repo

**Comment by bboyho** [comment]
### Incorrect Value Name in TB6612FNG Board Files
To clarify on @Funda 's issue, the value was incorrectly labeled for the package. Thus the part used in the board layout and schematic files was incorrectly labeled as _TB66**21**FNG_. The value should actually be labeled as _TB66**12**FNG_. This is just a minor issue and does not affect the overall board functionality or the board symbol/package that is used in the [SparkFun Eagle Libraries](https://github.com/sparkfun/SparkFun-Eagle-Libraries). 

These affect the schematic (PDF) and Eagle files (ZIP) for the following SKUs:

* [ROB-14451](https://www.sparkfun.com/products/14451) -- V11 Without Headers
* [ROB-09457](https://www.sparkfun.com/products/retired/9457) -- V10 Without Headers
* [ROB-14450](https://www.sparkfun.com/products/14450) -- V11 With Headers
* [ROB-13845](https://www.sparkfun.com/products/13845) -- V10 With Headers

### Artifacts from Cloning a Product Page
I have confirmed that the product page for [ROB-13845](https://www.sparkfun.com/products/13845) does indeed have the wrong schematic linked as @Funda stated. This is probably from the product page being cloned from the original ROB-9457 breakout board but was never updated. I will let catalog know after updating the board files and exporting the schematic as a PDF.

### SparkFun Eagle Library
@pbbob , by opening up the latest Eagle board files and right clicking on the symbol/package, it is listed under `SparkFun Eagle Libraries` >  `SparkFun-IC-Special-Function`.

**Comment by bboyho** [comment]
@Funda , Chris was able to update all the product pages. We are good now. =)
